### PR TITLE
Fixes faulty tooltip

### LINKED ISSUE #3222: Faulty tool tips on unscheduled sessions in  scheduler
This is how the tool tip looks on a scheduled session. 
image

However once a scheduled session is unscheduled , it appears in this form, where it is not supposed to appear. Only the sessions which have been unscheduled after being scheduled seem to behave like this. 
image

I would like to work on this.

### PR DESCRIPTION
**Pull request by CosmicCoder96**
fixes #3222 
giphy

### CODE REVIEW

File: app/static/js/events/scheduler.js [hunk 1]
```diff
@@ -342,9 +342,10 @@ function addSessionToUnscheduled(sessionRef, isFiltering, shouldBroadcast) {
     }
 
     try {
-        sessionRefObject.$sessionElement.popover('destroy');
-    } catch(ignored) { }
-
+        setTimeout( function() {
+            $('.session.unscheduled').popover('hide');}, 100);
```
Comment (niranjan94) [inline app/static/js/events/scheduler.js]: Align and indent the code properly. Make it more readable. Otherwise it's okay.

Comment (CosmicCoder96) [inline app/static/js/events/scheduler.js]: The delay is added because the issue was caused in the first place  due to asynchronous code.
And the popover('destroy'), did not delete the content inside the popover.

**Comment by CosmicCoder96** [comment]
@niranjan94 Thanks for the review, Done.
